# Aggregate Data

Check with Kim if this is needed and what exactly makes sense. 


*Kim's list of variables*

*in addition: proportion specificity*

In [3]:
import csv
import json
from collections import defaultdict
import pandas as pd
from collections import Counter
import os
import spacy

In [4]:
nlp = spacy.load("nl_core_news_sm")

In [5]:

ref_levels = [
    "individual-TG-levels",
    "middle-TG-levels",
    "high-TG-levels",
    "supra-TG-levels",
    
]

opp_target = ['OPP-TC-reference']


exclude =   [ "ChatGPT: punctution",
    "ChatGPT: emoji",
    "Misunderstood task",
    "No consent",
    "Less than 20 words",
    "No consent",
    "Did not finish the study",
    "WPM"]

In [113]:
# data[0]

In [121]:

def get_cat_info(target_category_dicts, target_labels, label_id):
    
    d = target_category_dicts[0]
    
    labels = []
    for l in target_labels:
        val = d[l].split(' ')
        for v in val:
            if v == label_id:
                labels.append(l)
    return ' '.join(labels)




def load_data(test_path):
    
    try:
        with open(test_path) as infile:
            data_original = list(csv.DictReader(infile, delimiter = ','))
    except FileNotFoundError:
        print('file not found')
        data_original = []
    return data_original



def get_exclude():
    

    
    exclude_dict = defaultdict(set)
    
    for d in full_id_data:
        text = d['lsid']
        for e in exclude:
            if d[e] == 'True':
                exclude[text].add(e)
    return exclude_dict

    
    

def process_file(test_path,  ref_levels, article_id_cond):

    data_out = []
    
    data_original = load_data(test_path)
    
    label_token_dicts = defaultdict(list)
    label_coref_dict = dict()
    label_behav_mapping = defaultdict(set)
    
    exclude = [
        "ChatGPT: punctution",
        "ChatGPT: emoji",
        "Misunderstood task",
        "No consent",
        "Less than 20 words",
        "No consent",
        "Did not finish the study",
        "WPM"]
        

    for d in data_original:
        if d['TC-reference'] != '':
            for label_id in d['TC-reference'].split(' '):
                label_token_dicts[label_id].append(d)
        if d['Behav-predicate'] != '':
            for label_id in d['Behav-predicate'].split(' '):
                if 'IkD2_fEYyH' == label_id:
                    print('Found problematic label')
                label_token_dicts[label_id].append(d)
        if d['OPP-TC-reference'] != '':
            for label_id in d['OPP-TC-reference'].split(' '):
                if 'IkD2_fEYyH' == label_id:
                    print('Found problematic label')
                label_token_dicts[label_id].append(d)        
        exclude_text = '-'
        for k in exclude:
            if k in d:
                v = d[k]
                if v != '':
                    exclude_text = v
                    


        if d['ref-id-relations'] != '':
            coref_ids = d['ref-id-relations'].split(' ')
            for coref_id in coref_ids:
                coref_list = coref_id.split('-_-')
                if len(coref_list) == 2:
                    coref_chain, label_id = coref_list
                    label_coref_dict[label_id] = coref_chain
                else:
                    print('problem')
                    print(coref_id)
                    print(coref_list)
            #     print(coref_chain, label_id)
            # print()

        # get mappings ref behav
        if d['behav-id-mapping'] != '':
            for ref_behav_mapping in d['behav-id-mapping'].split(' '):
                label_id1, label_id2 = ref_behav_mapping.split('-_-')
                label_behav_mapping[label_id1].add(label_id2)
                label_behav_mapping[label_id2].add(label_id1)
                
    if len(label_token_dicts) == 0:
        article_id, condition = article_id_cond.split(' ', 1)
        cond, ls_id = condition.split('_LS')
        d_out = dict()
        d_out['Article_id'] = article_id
        d_out['condition'] = cond
        d_out['lsid'] = ls_id

        # d_out['Topic'] = topic

        d_out['Referent_id'] = '-'
        d_out['Reference_text'] = '-'
        #get_cat_info(target_category_dicts, target_labels, label_id)
        d_out['Reference_level'] = '-'
        d_out['Opposite_target_category'] = '-'
        data_out.append(d_out)
        
        
    for label, token_dicts in label_token_dicts.items():
        tokens = ' '.join([d['token'] for d in token_dicts])
    
        
        
        if label in label_coref_dict:
            # print(token_dicts[0].keys())
            

            if label in label_behav_mapping:
                # print('Description found')
                behav_labels = label_behav_mapping[label]
                for behav_label in behav_labels:
                    
                    behav_token_dicts = label_token_dicts[behav_label]
                    if len(behav_token_dicts) == 0:
                        print('Problem')
                        print(behav_label)
                        print(behav_token_dicts)
                    tokens_behav = ' '.join([d['token'] for d in behav_token_dicts])
                    
                    d_out = dict()
                    coref = label_coref_dict[label]
                    # d_out['Reference'] = tokens
                    # d_out['coref'] = coref

                    # d_out['Newspaper_id'] = news_id
                    # print(article_id_cond)
                    article_id, condition = article_id_cond.split(' ', 1)
                    cond, ls_id = condition.split('_LS')
                    d_out['Article_id'] = article_id
                    d_out['condition'] = cond
                    d_out['lsid'] = ls_id
                    
                    # d_out['Topic'] = topic

                    d_out['Referent_id'] = coref
                    d_out['Reference_text'] = tokens
                    #get_cat_info(target_category_dicts, target_labels, label_id)
                    d_out['Reference_level'] = get_cat_info(token_dicts, ref_levels, label)
                    d_out['Opposite_target_category'] = get_cat_info(token_dicts, opp_target, label)
                    
                    data_out.append(d_out)
            elif label not in label_behav_mapping:
                d_out = dict()
                if label in label_coref_dict:
                    coref = label_coref_dict[label]
                else:
                    coref = ''
          
                # print(article_id_cond)
                article_id, condition = article_id_cond.split(' ', 1)
                # print(condition)
                cond, ls_id = condition.split('_LS')
                d_out['Article_id'] = article_id
                d_out['condition'] = cond
                d_out['lsid'] = ls_id
                # d_out['Topic'] = topic

                d_out['Referent_id'] = coref
                d_out['Reference_text'] = tokens
                d_out['Reference_level'] = get_cat_info(token_dicts, ref_levels, label)
                d_out['Opposite_target_category'] = get_cat_info(token_dicts, opp_target, label)
         
 
                data_out.append(d_out)
                
                
               

        elif label not in label_coref_dict and label not in label_behav_mapping:
            # print('this weird condition')
            # print('found label not in coref dict', label)
            # print('Description only')
            
            # d_out['Newspaper_id'] = news_id
            # d_out['Lstudio_id'] = ls_id
            article_id, condition = article_id_cond.split(' ', 1)
            cond, ls_id = condition.split('_LS')
            opp = get_cat_info(token_dicts, opp_target, label)
            ref = get_cat_info(token_dicts, ref_levels, label)
            
            if opp != '' or ref != '':
                d_out = dict()
                if label in label_coref_dict:
                    coref = label_coref_dict[label]
                else:
                    coref = ''
                d_out['Article_id'] = article_id
                d_out['condition'] = cond

                # d_out['Topic'] = topic
                d_out['lsid'] = ls_id

                d_out['Referent_id'] = coref
                d_out['Reference_text'] = tokens
                d_out['Reference_level'] = get_cat_info(token_dicts, ref_levels, label)
                d_out['Opposite_target_category'] = get_cat_info(token_dicts, opp_target, label)
                # print(get_cat_info(token_dicts, opp_target, label))
 

                data_out.append(d_out)

    

    return data_out, exclude_text

In [122]:

test_path = f'../results/kim-full-data-update1/output-5751477b947a3d0007b53c2c Klassiek jong txt_LS-id1334.csv'

article_id = 'output-5751477b947a3d0007b53c2c Klassiek jong txt_LS-id1334'
# topic = 'test'
# news_id = 'test'

#results/kim-full-data-update1/output-5751477b947a3d0007b53c2c Bridge jong txt_LS-id1333.csv

data_out = []

data_original = load_data(test_path)


data_out, exclude_text = process_file(test_path, ref_levels, article_id)
print(exclude_text)

df = pd.DataFrame(data_out)

df[:50]

-

,Article_id,condition,lsid,Referent_id,Reference_text,Reference_level,Opposite_target_category
0,output-5751477b947a3d0007b53c2c,Klassiek jong txt,-id1334,1,de inwoners,high-TG-levels,
1,output-5751477b947a3d0007b53c2c,Klassiek jong txt,-id1334,0,enkelen die behoefte hebben om naar klassieke ...,middle-TG-levels,
2,output-5751477b947a3d0007b53c2c,Klassiek jong txt,-id1334,0,ze,middle-TG-levels,
3,output-5751477b947a3d0007b53c2c,Klassiek jong txt,-id1334,0,Deze mensen,middle-TG-levels,
4,output-5751477b947a3d0007b53c2c,Klassiek jong txt,-id1334,0,ze,middle-TG-levels,

In [123]:
all_paths = os.listdir('../results/kim-full-data-update1/')

In [124]:
full_id_data = []
for path in all_paths:
    # print(path)
    article_id = path.strip('.csv')
    # print(article_id)
    full_path = f'../results/kim-full-data-update1/{path}'
 
    # print(full_path)
    if full_path.endswith('.csv'):
        id_data, exclude = process_file(full_path, ref_levels, article_id)
        for d in id_data:
            d['exclude'] = exclude
        full_id_data.extend(id_data)

In [125]:
test_out = f'../results/kim-full-data-update1.xlsx'

df = pd.DataFrame(full_id_data)

df.to_excel(test_out, sheet_name='Sheet1', na_rep='', float_format=None, 
            columns=None, header=True, index=False)

/var/folders/y9/gpzq16dd7sd129brk7fnpzn00000gn/T/ipykernel_84752/3090032428.py:5: UserWarning: Pandas requires version '3.0.5' or newer of 'xlsxwriter' (version '3.0.3' currently installed).
  df.to_excel(test_out, sheet_name='Sheet1', na_rep='', float_format=None,

In [120]:
df[:10]

,Article_id,condition,lsid,Referent_id,Reference_text,Reference_level,Opposite_target_category
0,output-5751477b947a3d0007b53c2c,Klassiek jong txt,-id1334,1,de inwoners,high-TG-levels,
1,output-5751477b947a3d0007b53c2c,Klassiek jong txt,-id1334,0,enkelen die behoefte hebben om naar klassieke ...,middle-TG-levels,
2,output-5751477b947a3d0007b53c2c,Klassiek jong txt,-id1334,0,ze,middle-TG-levels,
3,output-5751477b947a3d0007b53c2c,Klassiek jong txt,-id1334,0,Deze mensen,middle-TG-levels,
4,output-5751477b947a3d0007b53c2c,Klassiek jong txt,-id1334,0,ze,middle-TG-levels,

# Variables for Kim

* Degree of generalization in references = ((Aantal ‘individual’-references x 1) + (Aantal ‘subgroup’-references x 2) + (Aantal ‘TC’-references x 3) + (Aantal ‘supra’-references x 4)) / (Totaal aantal references)
* Proportion of individual-level references = (Aantal ‘individual’-level references) / (Totaal aantal references)
* Proportion of subgroup-level references = (Aantal ‘subgroup-level references) / (Totaal aantal references)
* Proportion of TC-level references = (Aantal ‘TC-level references) / (Totaal aantal references)
* Proportion of supra-level references = (Aantal ‘supra-level references) / (Totaal aantal references)
* Number of words in overall text
* Mean number of words devoted to each reference = (Aantal woorden besteed aan referenties) / (totaal aantal referenties in een tekst)
* Number of referents (co-reference chains) per 100 woorden = (Aantal referents (co-reference chains) / totaal aantal woorden in een tekst) x 100

## Degree of generalization and proportion level

In [126]:
full_id_data[:3]

[{'Article_id': 'output-pinl5476578eb2e6-13656072110e',
  'condition': 'Bingo oud txt.1',
  'lsid': '-id2229',
  'Referent_id': '0',
  'Reference_text': 'alle bewoners , behalve de immer knorrige Harry en Truus',
  'Reference_level': 'middle-TG-levels',
  'Opposite_target_category': '',
  'exclude': '-'},
 {'Article_id': 'output-pinl5476578eb2e6-13656072110e',
  'condition': 'Bingo oud txt.1',
  'lsid': '-id2229',
  'Referent_id': '0',
  'Reference_text': 'de bewoners',
  'Reference_level': 'middle-TG-levels',
  'Opposite_target_category': '',
  'exclude': '-'},
 {'Article_id': 'output-pinl5476578eb2e6-13656072110e',
  'condition': 'Bingo oud txt.1',
  'lsid': '-id2229',
  'Referent_id': '0',
  'Reference_text': 'elkaar',
  'Reference_level': 'middle-TG-levels',
  'Opposite_target_category': '',
  'exclude': '-'}]

In [127]:
def get_text_id_dict(full_id_data):
    
    text_id_dict = defaultdict(dict)
    for d in full_id_data:
        ls_id = d['lsid']
        text_id_dict[ls_id]['Article_id'] = d['Article_id']
        text_id_dict[ls_id]['condition'] = d['condition']
    return text_id_dict

def get_exclude_dict(full_id_data):
    
    text_exclude_dict = dict()
    
    for d in full_id_data:
        exclude = d['exclude']
        text = d['lsid']
        text_exclude_dict[text] = exclude
    return text_exclude_dict

def degree_generalization(full_id_data):
    
    gen_dict = dict()
    gen_dict['individual-TG-levels'] = 1
    gen_dict['middle-TG-levels'] = 2
    gen_dict['high-TG-levels'] = 3
    gen_dict['supra-TG-levels'] = 4
    
    text_dict = defaultdict(list)
    text_gen_dict = dict()
    for d in full_id_data:
        text_dict[d['lsid']].append(d['Reference_level'])

        
    for text, refs in text_dict.items():
        scores = []
        n_refs = len(refs)
        for tc_level, factor in gen_dict.items():
            c = refs.count(tc_level)
            scores.append(c * factor)
        text_gen_dict[text] = sum(scores)/n_refs
    
    return text_gen_dict

def prop_generalization(full_id_data, level):
    
    
    text_dict = defaultdict(list)
    text_gen_dict = dict()
    for d in full_id_data:
        text_dict[d['lsid']].append(d['Reference_level'])
        
    for text, refs in text_dict.items():

        n_refs = len(refs)
        c = refs.count(level)
        prop = c/n_refs
        text_gen_dict[text] = prop
    
    return text_gen_dict

def prop_opp_target_cat(full_id_data):
    
    
    text_dict = defaultdict(list)
    text_opp_dict = dict()
    for d in full_id_data:
        opp = d['Opposite_target_category']
        if opp != '':
            text_dict[d['lsid']].append(opp)
        text_dict[d['lsid']].append(d['Reference_level'])
        
    for text, refs in text_dict.items():

        n_refs = len(refs)
        c = refs.count('OPP-TC-reference')
        if n_refs != 0:
            prop = c/n_refs
        else:
            prop = 0
        text_opp_dict[text] = prop
    
    return text_opp_dict

In [128]:
text_id_dict = get_text_id_dict(full_id_data)
text_exclude_dict = get_exclude_dict(full_id_data)
text_gen_dict = degree_generalization(full_id_data)

prop_ind = prop_generalization(full_id_data, 'individual-TG-levels')
prop_sub = prop_generalization(full_id_data, 'middle-TG-levels')
prop_high = prop_generalization(full_id_data, 'high-TG-levels')
prop_super = prop_generalization(full_id_data, 'supra-TG-levels')

out_path = '../variables/generalization-references.csv'

gen_data = []
for text, gen_score in text_gen_dict.items():
    text_dict = text_id_dict[text]
    text_dict['ls-id'] = text
    text_dict['ref-generalization_score'] = gen_score
    text_dict['exclude'] = text_exclude_dict[text]
    gen_data.append(text_dict)
    
header = gen_data[0].keys()

with open(out_path, 'w') as outfile:
    writer = csv.DictWriter(outfile, fieldnames = header, delimiter = ',')
    writer.writeheader()
    for d in gen_data:
        writer.writerow(d)
        

# print(full_id_data[0].keys())       
text_id_dict = get_text_id_dict(full_id_data)
gen_prop_data = []

for text, prop_score_ind in prop_ind.items():
    prop_score_sub = prop_sub[text]
    prop_score_high = prop_high[text]
    prop_score_super = prop_super[text]
    text_dict = text_id_dict[text]
    text_dict['ls-id'] = text
    text_dict['individual-TG-levels'] = prop_score_ind
    text_dict['middle-TG-levels'] = prop_score_sub
    text_dict['high-TG-levels'] = prop_score_high
    text_dict['supra-TG-levels'] = prop_score_super
    text_dict['exclude'] = text_exclude_dict[text]
    gen_prop_data.append(text_dict)
    

out_path = '../variables/generalization-proportion-references.csv'
header = gen_prop_data[0].keys()

with open(out_path, 'w') as outfile:
    writer = csv.DictWriter(outfile, fieldnames = header, delimiter = ',')
    writer.writeheader()
    for d in gen_prop_data:
        writer.writerow(d)


        
text_id_dict = get_text_id_dict(full_id_data)
text_opp_dict = prop_opp_target_cat(full_id_data)    
opp_data = []
for text, opp_score in text_opp_dict.items():
    text_dict = text_id_dict[text]
    text_dict['ls-id'] = text
    text_dict['ref-opposite_prop'] = opp_score
    text_dict['exclude'] = text_exclude_dict[text]
    opp_data.append(text_dict)
        
out_path = '../variables/opposite-references-proportion.csv'
header = opp_data[0].keys()

with open(out_path, 'w') as outfile:
    writer = csv.DictWriter(outfile, fieldnames = header, delimiter = ',')
    writer.writeheader()
    for d in opp_data:
        writer.writerow(d)

## References and words in reference

* Number of words in text overall
* Mean number of words devoted to each reference = (Aantal woorden besteed aan referenties) / (totaal aantal referenties in een tekst)
* Number of referents (co-reference chains) per 100 woorden = (Aantal referents (co-reference chains) / totaal aantal woorden in een tekst) x 100

In [134]:
def get_text_id_dict(full_id_data):
    
    text_id_dict = defaultdict(dict)
    for d in full_id_data:
        ls_id = d['lsid']
        text_id_dict[ls_id]['Article_id'] = d['Article_id']
        text_id_dict[ls_id]['condition'] = d['condition']
    return text_id_dict



def get_word_dict(annotation_data):
    
    text_word_dict = dict()
    for an in annotation_data:
        ls_id = an['id']
        text = an['data']['text'].split('\n')[1][6:]
        text_word_dict[f'-id{ls_id}'] = text
    return text_word_dict
        

def n_referents(full_id_data, n_words_dict):
    
    text_dict = defaultdict(list)
    text_ref_dict = dict()
    text_refs_set = defaultdict(set)
    for d in full_id_data:
        coref_chain = d['Referent_id']
        target_cat = d['Reference_level']
        text = d['lsid']
        if target_cat != '-':
            text_refs_set[text].add(coref_chain)
    for text, coref_chains in text_refs_set.items():
        n_coref = len(coref_chains)
        n_words = n_words_dict[text]
        if n_words != 0:
            n_coref_prop = n_coref/n_words
        else:
            n_coref_prop = 0
        text_ref_dict[text] = n_coref_prop * 100

    return text_ref_dict


def n_words_reference(full_id_data, n_words_dict):
    
    text_n_words_ref = defaultdict(list)
    mean_words_ref_text = dict()
    
    for d in full_id_data:
        text = d['lsid']
        ref_text = d['Reference_text']
        target_cat = d['Reference_level']
        if target_cat != '-':
            doc_ref = nlp(ref_text)
            n_words_ref = len(doc_ref)
            text_n_words_ref[text].append(n_words_ref)
    
    for text, n_words in text_n_words_ref.items():
        total = sum(n_words)
        mean = total/len(n_words)
        mean_words_ref_text[text] = mean
    return mean_words_ref_text

In [135]:
path_ann = '../data/kim-full-data-update1.json'
with open(path_ann) as infile:
    annotation_data = json.load(infile)

text_word_dict = get_word_dict(annotation_data)
text_n_words_dict = dict()
text_id_dict = get_text_id_dict(full_id_data) 
text_exclude_dict = get_exclude_dict(full_id_data)

data_n_words = []

for text, text_dict in text_id_dict.items():
    part_text = text_word_dict[text]
    doc = nlp(part_text)
    n_words = len(doc)
    text_n_words_dict[text] = n_words
    text_dict['ls-id'] = text
    text_dict['n_words'] = n_words
    text_dict['exclude'] = text_exclude_dict[text]
    data_n_words.append(text_dict)
    
    
out_path = '../variables/n_words_text.csv'
header = data_n_words[0].keys()

with open(out_path, 'w') as outfile:
    writer = csv.DictWriter(outfile, fieldnames = header, delimiter = ',')
    writer.writeheader()
    for d in data_n_words:
        writer.writerow(d)

In [136]:
out_path = '../variables/mean_words_ref_text.csv'

data_mean_words_ref = []
text_id_dict = get_text_id_dict(full_id_data) 
text_mean_words_ref = n_words_reference(full_id_data, text_n_words_dict)

for text, mean in text_mean_words_ref.items():
    text_dict = text_id_dict[text]
    text_dict['ls-id'] = text
    text_dict['mean_words_ref'] = mean
    text_dict['exclude'] = text_exclude_dict[text]
    data_mean_words_ref.append(text_dict)

header = data_mean_words_ref[0].keys()

with open(out_path, 'w') as outfile:
    writer = csv.DictWriter(outfile, fieldnames = header, delimiter = ',')
    writer.writeheader()
    for d in data_mean_words_ref:
        writer.writerow(d)

In [137]:
out_path = '../variables/n_words_ref_100.csv'

data_n_ref = []
text_id_dict = get_text_id_dict(full_id_data) 
text_n_ref_dict =  n_referents(full_id_data, text_n_words_dict)

for text, n_ref in text_n_ref_dict.items():
    text_dict = text_id_dict[text]
    text_dict['ls-id'] = text
    text_dict['n_refs_100'] = n_ref
    text_dict['exclude'] = text_exclude_dict[text]
    data_n_ref.append(text_dict)

header = data_n_ref[0].keys()

with open(out_path, 'w') as outfile:
    writer = csv.DictWriter(outfile, fieldnames = header, delimiter = ',')
    writer.writeheader()
    for d in data_n_ref:
        writer.writerow(d)